replicaCount: 2

image:
  repository: "{{ECR_REGISTRY}}/lesson-8-ecr"   # Jenkins замінить на реальний URL
  tag: "latest"                                 # ← Jenkins буде міняти саме цей рядок
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

config:
  name: django-app-config
  environmentVariables:
    SECRET_KEY: "django-insecure-i-l9b6thb-4iv@$#fvps%ee588$%3=7(%d(2r@@@((#q&wgg1k"
    DEBUG: "False"
    ALLOWED_HOSTS: "*"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70